# Generated by Django 4.1.2 on 2022-10-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='edad',
            new_name='años',
        ),
    ]
