# Generated by Django 4.1.2 on 2022-10-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0002_rename_edad_animal_años'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='años',
            new_name='edad',
        ),
    ]
